### ISSUE TITLE
Are there any specific compiler settings aside from std++17 (onwards) I need to get this to work?

### ISSUE THREAD

**Issue by oviano** [maxbachmann/rapidfuzz-cpp#105]
I was using version 0.0.1 of the amalgamation from I guess a couple of years ago and I was able to drop this into my project and it built and I could use it fine.

Today I tried the latest amalgamation, and I get all these weird errors in Xcode, and similar under MSVC:

I had a look at CMakeLists.txt but aside from specifying that C++17 is required, I couldn't spot anything else I need.

I have specified C++20 in my own project, but I get the same errors if I change it to C++17.

<img width="1724" alt="Screenshot 2023-05-09 at 18 15 26" src="https://github.com/maxbachmann/rapidfuzz-cpp/assets/621629/f6e18c36-1013-4df7-a173-82ae32620cdd">

**Comment by oviano** [comment]
Ok, I think I just need to better understand the newer API, so I'm closing this now.

**Comment by maxbachmann** [comment]
I think this should just be `CachedRatio<char>` now and `scorer.similarity` now.

**Comment by maxbachmann** [comment]
and you might want to pass `CachedRatio` as `const &`, since it is not modified by the score calculation.

**Comment by oviano** [comment]
Yes, thank you, I figured that out in the end! I was using a version from quite a while ago.

Anyway, thanks for the library!
