### ISSUE TITLE
Compare c++ with python

### ISSUE THREAD

**Issue by xiaocaoxu** [maxbachmann/rapidfuzz-cpp#19]
hello, the c++ version is slower than python version on my computer,i don't know what causes this problem?

**Comment by maxbachmann** [comment]
how did you compile the C++ version?

**Comment by xiaocaoxu** [comment]
thank you for your reply, According to your suggestion it really improved the speed,but its speed is slower than python version, rapidfuzz::fuzz::ratio(s1, s2) is the method i need to use, s1 and s2 are He and she are two different Chinese string with a length of 1000 characters, use time 10 milliseconds in c++ and 0.9 millisecond in python, the integration method I use is Add this repository as a submodule, Looking forward to your reply.

**Comment by xiaocaoxu** [comment]
thank you for your reply, According to your suggestion it really improved the speed,but its speed is slower than python version, rapidfuzz::fuzz::ratio(s1, s2) is the method i need to use, s1 and s2 are two different Chinese string with a length of 1000 characters, use time 10 milliseconds in c++ and 0.9 millisecond in python, the integration method I use is Add this repository as a submodule, Looking forward to your reply.

**Comment by maxbachmann** [comment]
The Python version directly calls the C++ version, so it should not be faster. I did just do a quick test, in which they performed about similar (on my system both took around 1ms for 1k characters). The python version is compiled with the optimisation level 2, which should be the default for Release mode in cmake aswell. Could you share your performance test with me?

**Comment by xiaocaoxu** [comment]
Thank you, i have sent my test file to your emali.

**Comment by maxbachmann** [comment]
Your problem is, that in C++ you read the file into std::string. If you check the length e.g. of the first std::string it has 3000 characters. For chinese you will have to use a different string type like std::wstring.
Since ratio is using the Levenshtein distance, which is O(N*N) your doing 3*3=9 times the work in your C++ implementation right now.

**Comment by xiaocaoxu** [comment]
Thank you very much for your answer. It helped me a lot.
