### ISSUE TITLE
get_maching_blocks problem.

### ISSUE THREAD

**Issue by fizzyade** [maxbachmann/rapidfuzz-cpp#26]
Trying to use the library for my application, it works fine when compiling on macOS, but under Windows using the msvc 2019 compiler, I get the following error:

error C2039: 'get_matching_blocks': is not a member of 'rapidfuzz::fuzz::detail'

No matter what I've tried, I cannot get the code to compile.

Any ideas?

**Comment by maxbachmann** [comment]
Ah yes I did run into this with my python implementation as well and fixed it on my current development branch (I really need to add a CI to the C++ repository, so I do not only catch issues with the Python build).
The lastest master commithttps://github.com/maxbachmann/rapidfuzz-cpp/commit/a75c1da0804cd5a5a2b5e398d2d9403fd3627a7b should fix this issue

**Comment by fizzyade** [comment]
Cool.  Thanks for the prompt response!  

I just removed the code from my project to get it building again but will undo my commit and add the library back in.  I'll let you know how I get on.

**Comment by fizzyade** [comment]
ok, it compiles and works now, however, it emits a load of warnings when compiling. (don't you love MSVC)
```cpp
FavouritesSortProxyFilterModel.cpp
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\details/common.hpp(190): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz/fuzz.hpp(52): note: see reference to function template instantiation 'rapidfuzz::common::PatternMatchVector<1>::PatternMatchVector<char>(std::basic_string_view<char,std::char_traits<char>>)' being compiled
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz/fuzz.hpp(51): note: while compiling class template member function 'rapidfuzz::fuzz::CachedRatio<std::basic_string_view<char,std::char_traits<char>>>::CachedRatio(const Sentence1 &)'
        with
        [
            Sentence1=std::basic_string_view<char,std::char_traits<char>>
        ]
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\fuzz_impl.hpp(64): note: see reference to function template instantiation 'rapidfuzz::fuzz::CachedRatio<std::basic_string_view<char,std::char_traits<char>>>::CachedRatio(const Sentence1 &)' being compiled
        with
        [
            Sentence1=std::basic_string_view<char,std::char_traits<char>>
        ]
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\fuzz_impl.hpp(64): note: see reference to class template instantiation 'rapidfuzz::fuzz::CachedRatio<std::basic_string_view<char,std::char_traits<char>>>' being compiled
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\components\RouteAnalyser\FavouritesSortProxyFilterModel.cpp(45): note: see reference to function template instantiation 'rapidfuzz::percent rapidfuzz::fuzz::partial_ratio<std::string,std::string,char,char>(const Sentence1 &,const Sentence2 &,rapidfuzz::percent)' being compiled
        with
        [
            Sentence1=std::string,
            Sentence2=std::string
        ]
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\details/string_metrics/weighted_levenshtein_impl.hpp(138): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\details/string_metrics/weighted_levenshtein_impl.hpp(293): note: see reference to function template instantiation 'size_t rapidfuzz::string_metric::detail::weighted_levenshtein_bitpal<char,char>(std::basic_string_view<char,std::char_traits<char>>,std::basic_string_view<char,std::char_traits<char>>)' being compiled
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\details/string_metrics/weighted_levenshtein_impl.hpp(337): note: see reference to function template instantiation 'size_t rapidfuzz::string_metric::detail::weighted_levenshtein<char,char>(std::basic_string_view<char,std::char_traits<char>>,std::basic_string_view<char,std::char_traits<char>>,size_t)' being compiled
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\string_metric.hpp(259): note: see reference to function template instantiation 'double rapidfuzz::string_metric::detail::normalized_weighted_levenshtein<char,char>(std::basic_string_view<char,std::char_traits<char>>,std::basic_string_view<char,std::char_traits<char>>,const double)' being compiled
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\fuzz_impl.hpp(24): note: see reference to function template instantiation 'double rapidfuzz::string_metric::normalized_levenshtein<Sentence1,Sentence2>(const Sentence1 &,const Sentence2 &,rapidfuzz::LevenshteinWeightTable,double)' being compiled
        with
        [
            Sentence1=std::basic_string_view<char,std::char_traits<char>>,
            Sentence2=std::basic_string_view<char,std::char_traits<char>>
        ]
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\fuzz_impl.hpp(38): note: see reference to function template instantiation 'rapidfuzz::percent rapidfuzz::fuzz::ratio<std::basic_string_view<char,std::char_traits<char>>,std::basic_string_view<char,std::char_traits<char>>>(const Sentence1 &,const Sentence2 &,const rapidfuzz::percent)' being compiled
        with
        [
            Sentence1=std::basic_string_view<char,std::char_traits<char>>,
            Sentence2=std::basic_string_view<char,std::char_traits<char>>
        ]
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\fuzz_impl.hpp(80): note: see reference to function template instantiation 'double rapidfuzz::fuzz::CachedRatio<std::basic_string_view<char,std::char_traits<char>>>::ratio<std::basic_string_view<char,std::char_traits<char>>>(const Sentence2 &,rapidfuzz::percent) const' being compiled
        with
        [
            Sentence2=std::basic_string_view<char,std::char_traits<char>>
        ]
C:\Users\adriancarpenter\Documents\Development\pingnoo\src\libs\3rdparty\rapidfuzz-cpp\rapidfuzz\fuzz_impl.hpp(80): note: see reference to function template instantiation 'double rapidfuzz::fuzz::CachedRatio<std::basic_string_view<char,std::char_traits<char>>>::ratio<std::basic_string_view<char,std::char_traits<char>>>(const Sentence2 &,rapidfuzz::percent) const' being compiled
        with
        [
            Sentence2=std::basic_string_view<char,std::char_traits<char>>
        ]
```

**Comment by maxbachmann** [comment]
Yes MSVC tends to be stricter with some of their warnings. I personally do not use Windows and gcc does not emit any warnings at least with `-Wall`. I often see similar warnings when failing Windows compilations of the Python implementation as well. It would probably help to add a CI build for platforms like Windows, but each time I look at ci builds for CMake in GitHub Actions appear to be a pain. E.g. https://github.com/cristianadam/HelloWorld/blob/master/.github/workflows/build_cmake.yml implements one for all platforms, but does not even take care of things like Catch2, Google Benchmark and Boost builds we need for the tests/benchmarks of RapidFuzz. I opened a issue on this topic, since I planned to do this since a very long time, but just can not get myself to actually implement it. Maybe someone else is faster than me. 
Pull Requests to fix these sort of issues are welcome, but as long as they are not tested in the CI I will probably reintroduce similar warnings :disappointed_relieved:

**Comment by fizzyade** [comment]
I created a pull request, but master has moved on and the commits I made aren't compatible.

The issue is that you use loops of size_t and then pass the value into other templates that are expecting int.  Under MSVC this throws up a warning.

I fixed the specific issue for my usage case, but it probably needs fixing in more places.

**Comment by maxbachmann** [comment]
I fixed a couple more of those warnings in MSVC: https://github.com/maxbachmann/rapidfuzz-cpp/commit/758276b8f8f0eff81dcbfc53edeb97fe2aa819f6

**Comment by fizzyade** [comment]
I guessed there would be more as I'm only using a couple of functions, I did try to find ones of the same type that I was having appear.

**Comment by maxbachmann** [comment]
Yes I finally activated '/W4' on my Python Wrapper build, which brought up a few warnings in my code and a few in the code generated by Cython. Slowly fixing them as I encounter them.

**Comment by fizzyade** [comment]
> Yes I finally activated '/W4' on my Python Wrapper build, which brought up a few warnings in my code and a few in the code generated by Cython. Slowly fixing them as I encounter them.

As an aside, is there any good documentation on making the most of this?  I'm using it very simply and probably not to its full effect.

I'm using it in my app to "fuzzy" search for "bookmarks".  These bookmarks are hierarchical, so as an example:

"Europe/London/Cloudflare"

I split the string by "/" and then I apply the partial match on each segment (3 in this example), if the partial match of any part is above a threshold, then the item is added to the filtered display.
