### ISSUE TITLE
Tiny build issue: require Catch2 >= 3.0

### ISSUE THREAD

**Issue by emmenlau** [maxbachmann/rapidfuzz-cpp#36]
I think `rapidfuzz-cpp` requires `Catch2` version >= 3.0, is that possible? I could not build against 2.13.4, the latest official release. Its really no big issue for me, but it may be helpful for users if you set
```
find_package(Catch2 3.0.0 REQUIRED)
```
in `test/CMakeLists.txt`.

**Comment by maxbachmann** [comment]
Yes I use the latest v3.0.0 preview. Updated it accordingly.
