### ISSUE TITLE
CMake Integration does not work

### ISSUE THREAD

**Issue by jkryszyn** [maxbachmann/rapidfuzz-cpp#40]
Hello,
is CMake Integration described in radme actually works? I am doing exactly as it is said in "Installing it" section, but all I get in my project is:

By not providing "Findrapidfuzz.cmake" in CMAKE_MODULE_PATH this project [cmake]  has asked CMake to find a package configuration file provided by [cmake]   "rapidfuzz", but CMake did not find one.

I am doing it on Ubuntu 20.04.

**Comment by maxbachmann** [comment]
I just tested it and it does not work for me either.
A Pull Request fixing this would be welcome. Otherwise I should have time to look into this next week.

**Comment by jkryszyn** [comment]
Sadly my knowledge of CMake is very limited. I am afraid I won't be able to contribute.

**Comment by maxbachmann** [comment]
I finally fixed this.
