### ISSUE TITLE
Suggestion to use relative includes for internally included hpp files...

### ISSUE THREAD

**Issue by oviano** [maxbachmann/rapidfuzz-cpp#41]
...at the moment, the files refer to things like <rapidfuzz/detail...> etc when including.

If it instead picked up the headers relative to the location (no <> angled brackets) then it becomes really easy to drop the library into an existing project as a header-only library.

Nice library, by the way :)

**Comment by maxbachmann** [comment]
I will look into this, so this does not break anything.
For your use case I actually generate a single header file you can directly drop into an existing project: https://github.com/maxbachmann/rapidfuzz-cpp/blob/master/extras/rapidfuzz_amalgamated.hpp

**Comment by oviano** [comment]
Oh that's great, I hadn't seen that. Thank you very much!

**Comment by maxbachmann** [comment]
No problem. It is not documented anywhere yet :sweat_smile:
