### ISSUE TITLE
sorted_split increments the iterator to one-past-end

### ISSUE THREAD

**Issue by AntonShalgachev** [maxbachmann/rapidfuzz-cpp#74]
Hi!
I've noticed that `common::sorted_split` increments the iterator to one-past-end, which is caught by the bounds check in `std::string` and `std::string_view` (and probably in other STL containers as well) and results in a crash (at least on Windows on Debug configuration):

```cpp
for (; second != last && first != last; first = second + 1) {
    second = std::find_if(first, last, is_space<CharT>);

    if (first != second) {
        splitted.emplace_back(first, second);
    }
}
```

More specifically, if `std::find_if` returns 'last', then the iteration expression `first = second + 1` would effectively increment the "end" iterator, which seems to be UB (although I probably won't be able to find a quote from the standard)

The issue happens for me when using the `CachedTokenSortRatio`.

For what it's worth, here's the fix that's working for me:
```cpp
for (; second != last && first != last; first = second + 1) {
    // ...
    if (second == last)
        break;
}
```

I'll create a PR in the near future to resolve this issue

Version: 1.0.1 (6642000b428b952de0fdf4d1f4be34e0b7b1eca3)
Compiler: MSVC 19.31.31104 (Visual Studio 2022 17.1.1)

**Comment by maxbachmann** [comment]
> More specifically, if std::find_if returns 'last', then the iteration expression first = second + 1 would effectively increment the "end" iterator, which seems to be UB (although I probably won't be able to find a quote from the standard)

Iterators might be raw pointers and at least for raw pointers incrementing more than one past the end of the memory region is undefined behavior. According to §5.7 ¶5 of the C++11 spec:
> If both the pointer operand and the result point to elements of the same array object, or one past the last element of the array object, the evaluation shall not produce an overflow; otherwise, the behavior is undefined.

**Comment by AntonShalgachev** [comment]
Awesome, thanks for the standard reference
