### ISSUE TITLE
What platorms are supported?

### ISSUE THREAD

**Issue by Creapermann** [maxbachmann/rapidfuzz-cpp#98]
I cant see the officially supported platforms in the README.md, what platforms does this library support?

**Comment by maxbachmann** [comment]
This library has very little platform specific code and should therefor work on most platforms. I personally largely use it through the Python library, which I package for: Windows (x86), Linux (both glibc and musl) (x86, arm, ppc, s390x), MacOS (x86, arm). Note that Linux ppc / s390x has very few users, so there might be problems I am simply not aware of. In addition I am aware of people using the library on Android and Free BSD. The officially supported compilers are gcc, clang and msvc, but additional compilers would be easy to support.

**Comment by Creapermann** [comment]
Great, I'll be able to use it for my application then. Thanks for the great work with your library, keep it up!
